version: "2.2"
services:
  my-postgres:
    image: postgres
    ports:
      - "9000:5432"
    environment:
      POSTGRES_USER: user_postgres
      POSTGRES_PASSWORD: pwd_postgres
      POSTGRES_DB: assignment
  my-app:
    image: fadelmajid/node-server
    depends_on:
      - my-postgres
    ports: 
      - "8585:8585"